name: Build and Release SAD

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build executable
        run: pyinstaller main.py --onefile --windowed --icon=icon.ico --hidden-import=importlib.resources

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: SAD-windows-exe
          path: dist/*.exe

  release:
    needs: build-windows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: SAD-windows-exe
          path: ./dist

      - name: Create Git tag
        id: tag
        run: |
          TAG=v$(date +'%Y.%m.%d-%H%M')
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: ./dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
